class Post < ApplicationRecord
  # extends ...................................................................
  extend FriendlyId

  # includes ..................................................................

  # relationships .............................................................
  belongs_to :user

  # validations ...............................................................
  validates :title, presence: true
  validates :body, presence: true
  validates :status, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  friendly_id :title, use: :slugged

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  # protected instance methods ................................................

  # private instance methods ..................................................
end